### ISSUE TITLE
Automação das commits com commitzen

### ISSUE THREAD

**Issue by tashima42** [GuenkaTreinamentos/treinamentos#11]
Assim como eu, acredito que quase todo mundo no projeto não tem muita experiência usando o conventional commits. Pra facilitar esse processo, me indicaram o [commitzen](https://github.com/commitizen/cz-cli), uma ferramenta que ajuda na automação das commits e a manter o padrão. 
A instalação pode ser feita por meio do yarn, o que simplifica muito o processo e a utilização também é extremamente simples, ao invés de `git commit -m "message"`, o comando `git cz` é utilizado, ele te guia por alguns passos para fazer a commit.

1. 
	```
	? Select the type of change that youre committing: (Use arrow keys)
	❯ feat:     A new feature 
	  fix:      A bug fix 
	  docs:     Documentation only changes 
	  style:    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc) 
	  refactor: A code change that neither fixes a bug nor adds a feature 
	  perf:     A code change that improves performance 
	  test:     Adding missing tests or correcting existing tests 
	```
2. 
	``` 
	? Select the type of change that youre committing: docs:     Documentation only changes
	? What is the scope of this change (e.g. component or file name): (press enter to skip) 
	? Write a short, imperative tense description of the change (max 94 chars):
	 (4) test
	? Provide a longer description of the change: (press enter to skip)
	 
	? Are there any breaking changes? No
	? Does this change affect any open issues? No
	```

Vocês acham valido usar uma ferramenta como essa, ou desnecessário?

**Comment by devvaneio** [comment]
@Tashima42, acho legal a iniciativa. Para quem não estiver acostumado, é uma boa alternativa.
Vou adicionar como uma sugestão no README.md e quem tiver interesse pode instalar globalmente.
