### ISSUE TITLE
Conhecimentos em git e github

### ISSUE THREAD

**Issue by devvaneio** [GuenkaTreinamentos/treinamentos#12]
Time, gostaria de saber se vocês possuem todos ou alguns destes conhecimentos:

* Criar nova `branch`.
* Criar `pull request`.
* Fazer `rebase` and resolver conflitos.
* Usar os comandos `stash` e `reset`.
* Criar e usar chaves SSH.
* Mudar configurações de email e usuários do git.

Comentem abaixo, por favor.

**Comment by gabidepizol** [comment]
Então, eu usei muito pouco o git e github na faculdade (foi mais no final do curso mesmo), mas nunca cheguei a usar com outras pessoas (dar fork, criar branch, etc), 

- Criar nova branch - nunca tinha feito, mas nao tive dificuldades pra fazer ontem.
- Criar pull request - sei.
- Fazer rebase and resolver conflitos. - nunca fiz.
- Usar os comandos stash e reset. - ja vi videos sobre, mas nunca fiz.
- Criar e usar chaves SSH. - nunca fiz.
- Mudar configurações de email e usuários do git. - sei.

**Comment by tashima42** [comment]
Conheço todos esses comandos do git e os usos deles, mas não tenho muita experiência trabalhando com multiplas pessoas e branches. 
No windows já trabalhei com o Putty para chaves SSH, mas no linux nunca.

**Comment by renandmc** [comment]
- Criar nova branch: Sei fazer
- Criar pull request: Não sei se é a forma correta ou se tem alguma certa, mas consegui fazer ontem, dei push na branch depois criei a pull request pela interface do github.
- Fazer rebase and resolver conflitos: Essa parte tenho dúvidas, como não usava branches, usava o pull pra pegar a versão atual e corrigir os conflitos antes de fazer o push.
- Usar os comandos stash e reset: Nunca usei.
- Criar e usar chaves SSH: Me lembro de ter feito alguma vez, mas quando preciso consulto na Internet.
- Mudar configurações de email e usuários do git: Uso o git config normalmente (user.name / user.email)

**Comment by arrudaluiz** [comment]
Apesar de entender o comando `stash`, não tenho familiaridade com seu uso e também nunca utilizei chaves SSH.
