### ISSUE TITLE
Brainstorm meeting

### ISSUE THREAD

**Issue by devvaneio** [GuenkaTreinamentos/treinamentos#14]
Quem teve curiosidade a respeito do nome que eu sugeri para o nome da pasta do frontend(flashcards),
deve ter uma ideia do que mais ou menos eu quero propor como projeto.

[Link](https://www.educamaisbrasil.com.br/educacao/enem/saiba-o-que-sao-flashcards-e-como-eles-podem-te-ajudar-no-enem) para saber mais sobre flashcards.

Já existem alguns apps bem legais, como o [Anki](https://apps.ankiweb.net/), mas a ideia é construir algo mais voltado para programação e utilizar também a técnica de [repetição espaçada](https://medium.com/@AlfredBaudisch/flashcards-memoriza%C3%A7%C3%A3o-e-a-t%C3%A9cnica-da-repeti%C3%A7%C3%A3o-espa%C3%A7ada-ou-como-aprender-qualquer-coisa-2d721b0ddc54). É uma solução que eu sempre tive interesse em construir, mas talvez agora vocês consigam me ajudar nisso! 

Eu tenho várias ideias e quero ouvir as suas. Como descrito no repo, vocês já podem deixar suas dúvidas e sugestões aqui, mesmo antes desta reunião de brainstorm.

Link para o meet: https://meet.google.com/udc-oovb-mpc
Data: 06/08/20 e 07/08/20 às ~16hrs~ 14hrs

**Comment by tashima42** [comment]
Nessa reunião de brainstorm vão ser só ideias, ou vamos definir requisitos?

**Comment by devvaneio** [comment]
Inicialmente vamos tentar propor ideias e discutir abordagens. Mas se a gente evoluir bastante, podemos já também iniciar a parte da definição de requisitos.

**Comment by tashima42** [comment]
Achei esse [site](https://ankiweb.net/shared/decks/) onde pessoas compartilham decks do Anki com vários assuntos, uma ideia de feature poderia ser aproveitar essa biblioteca gigante usando um pacote como [esse](https://www.npmjs.com/package/anki-to-json), que converte APKG pra JSON.

**Comment by devvaneio** [comment]
@Tashima42, acho a ideia de importar estes dados muito interessante!

**Comment by gabidepizol** [comment]
pesquisei um pouco sobre design de telas de outros softwares com o mesmo objetivo do Anki, coloquei la no [Figma](https://www.figma.com/file/DekVqvjZWu9V7WouOfEIWG/treinamentoGuenka?node-id=1%3A4l), na página referências.

**Comment by devvaneio** [comment]
Legal, @gabidepizol.

**Comment by devvaneio** [comment]
Uma coisa legal também seria a gente incluir o suporte a Markdown(que nem estes comentários aqui nas issues) dentro do app, para a criação dos cards.
Talvez não para o card todo, mas apenas para o _body_. Então título, tags e outras coisas estariam à parte.

**Comment by tashima42** [comment]
Converti alguns decks para JSON e percebi uma coisa que pode ser um problema. O Anki aceita campos personalizados, o que pode atrapalhar bastante na hora de pegar esses dados convertidos. 
O deck base: https://github.com/Tashima42/anki-cli-clone/blob/anki-to-json-test/data/anki/testdeck.apkg
JSON gerado: https://github.com/Tashima42/anki-cli-clone/blob/anki-to-json-test/data/anki-to-json/testdeck/notes.json

**Comment by devvaneio** [comment]
@Tashima42, isso pode ser um problema para o frontend, mas no backend, usando o MongoDB (no-sql), a gente pode salvar schemeless.

**Comment by devvaneio** [comment]
Outra coisa, a gente também pode ignorar os campos adicionais. E acho que o ideal é que a gente faça um segundo parse (ou incluir neste) para mudar as chaves de acordo com o que a gente propor na solução.

**Comment by gabidepizol** [comment]
eu mexi um pouco no anki e listei alguns pontos positivos e negativos do sistema

pontos positivos:

- as estatisticas (mostrar o seu progresso é bem interessante)
- a opção de colocar áudio pra quem ta estudando idioma (mas pro foco de programação não seria tão útil assim)
- ele **avisa** sobre card duplicado

pontos negativos:

- um resumão é que ele é pouco intuitivo
- o botão de criar baralho é "escondido"
- ele deixa criar um card duplicado
- pra adicionar cards no deck ja criado é dificil
- não achei nenhum lugar que dê pra excluir um certo card
- e pra editar um card só é possível quando começa a estudar o deck inteiro

**Comment by devvaneio** [comment]
@gabidepizol, acredito que você bateu na tecla certa. O esforço cognitivo relacionado às funcionalidades é parte fundamental do processo.

Alguns links para saber mais sobre esforço cognifico:
* https://www.nngroup.com/articles/minimize-cognitive-load/
* https://www.invisionapp.com/design-defined/cognitive-load/

Eu particulamente gosto muito da interface do Nubank. Você não fica confuso com várias opções, o fluxo é bem direto a cada click que você realiza.

**Comment by devvaneio** [comment]
Uma feature que iremos precisar:

- Selecionar os cards que o usuário precisa revisar. Seria uma funcionalidade independente de baralho/deck, mas baseada nas revisões anteriores:

  - Criar um algoritmo de repetição espaçada (simples, pois estamos apenas fazendo um MVP) ou lib.
  - Seria estilo "feed" (não precisa ser rolagem necessariamente).

**Comment by tashima42** [comment]
Testei um pouco o algoritmo do Anki e acho que ele funciona como se fossem 3 pilhas. A primeira pilha é a principal que inicia com todos os cards, a segunda pilha é a dos que não serão mostrados novamente (marcados com easy) e a terceira é a que será mostrada no final (marcados com good). Quando um card é marcado com again, ele volta pra pilha principal em uma posição aleatória depois da que ele estava.

Exemplo: 
Total de números: 6
|posição|numero|dificuldade|
|-------|-------|----------|
|1|1|easy|
|2|2|again|
|3|3|easy|
|4|4|good|
|5|5|good|
|6|**2**|easy|
|7|6|easy|
|8|**4**|easy|
|9|**5**|easy|

**Comment by tashima42** [comment]
Uma coisa bacana pra organização seriam "salas de estudo", onde cada sala é específica para algum assunto e na hora de revisar o usuário pode escolher ver apenas os cards que envolvem programação, ou talvez só idiomas, etc.

**Comment by devvaneio** [comment]
@Tashima42, sala de estudo não seria a mesma coisa que baralhos? Ou tem alguma diferença que eu não entendi?

**Comment by devvaneio** [comment]
>Uma coisa bacana pra organização seriam "salas de estudo", onde cada sala é específica para algum assunto e na hora de revisar o usuário pode escolher ver apenas os cards que envolvem programação, ou talvez só idiomas, etc.

O algoritmo de repetição espaçada trabalha com intervalos de tempo. Como eu determinaria quando iria ser mostrado o primeiro card da pilha easy e da pilha good?

Ex: quantos cards easy seriam mostrados antes de um good ou todos os easy seriam mostrados antes?

**Comment by tashima42** [comment]
> @Tashima42, sala de estudo não seria a mesma coisa que baralhos? Ou tem alguma diferença que eu não entendi?

Seria como uma pasta onde tu guarda baralhos do mesmo assunto. O Anki tem uma coisa parecida com o esquema de livros dentro de baralhos, mas eu acho bem pouco intuitivo como funciona.

**Comment by devvaneio** [comment]
A gente poderia ter uma feature em que ele escolhe os baralhos que ele vai revisar. Mas sem adicionar mais
uma metáfora.

Ex: lista da baralhos e checkboxes para selecionar ou outra coisa com a mesma função.

**Comment by tashima42** [comment]
@lusatiro funciona com as tags que você mencionou também

**Comment by tashima42** [comment]
@lusatiro  o algoritmo que eu mencionei é pra quando já se tem uma lista de cards definida para uma seção de estudos. Não pensei muito ainda sobre como funicionaria o algoritmo de prioridade pra decidir o que vai pra uma seção. 

> Testei um pouco o algoritmo do Anki e acho que ele funciona como se fossem 3 pilhas. A primeira pilha é a principal que inicia com todos os cards, a segunda pilha é a dos que não serão mostrados novamente (marcados com easy) e a terceira é a que será mostrada no final (marcados com good). Quando um card é marcado com again, ele volta pra pilha principal em uma posição aleatória depois da que ele estava.

Esse algoritmo recebe uma lista de cards definida por outro e ignora as dificuldades marcadas em outras seções.

**Comment by devvaneio** [comment]
Acredito que o conceito de deck/baralho seja dispensável. Metáforas no desenvolvimento de software são muito importantes.
Porém mesmo no Anki existe a metáfora de tags. E na minha visão, aceito contra-argumentos, tags e decks são a mesma coisa, embora o usuário possa definir mais de uma tag para um card. Ainda sim você poderia revisar por tags. E as pesquisas podem ser feitas através das tags.
