### ISSUE TITLE
Instalando Git 2.28.0 no Ubuntu

### ISSUE THREAD

**Issue by tashima42** [GuenkaTreinamentos/treinamentos#15]
## Instalando ou atualizando
1. Adicione o PPA do Git: `sudo add-apt-repository ppa:git-core/ppa`
    > Se você não adicionar o PPA do Git ele será instalado, mas em uma versão antiga
2. Atualize os pacotes: `sudo apt update`
3. Instale o pacote: `sudo apt install git`
4. Verifique se ele está na versão mais recente: `git --version`
	- A resposta deve ser: `git version 2.28.0`

**Comment by devvaneio** [comment]
@Tashima42, o que acontece se já tiver outra versão do git instalada?

**Comment by tashima42** [comment]
> @Tashima42, o que acontece se já tiver outra versão do git instalada?

@lusatiro  testei em uma VM e ele só atualizou pra versão mais recente. Primeiro, coloquei um método de usar o próprio git pra se atualizar, mas quando fui testar não funcionou.

**Comment by lusatiro** [comment]
@Tashima42, me confundi agora. Você está usando Windows e rodando o Ubuntu numa VM? Ou tem dual boot e também rodou uma VM?

**Comment by tashima42** [comment]
> @Tashima42, me confundi agora. Você está usando Windows e rodando o Ubuntu numa VM? Ou tem dual boot e também rodou uma VM?

@lusatiro uso o Pop!_OS, que é baseado no Ubuntu e rodei uma VM com Ubuntu 20.04 nele pra testar.

**Comment by devvaneio** [comment]
Você disse mesmo. Que versão do git que está no seu PopOS?

**Comment by Tashima42** [comment]
Versão 20.04 LTS

**Comment by devvaneio** [comment]
Vou fechar a issue. Adicionando o PPA, no caso de estar usando Ubuntu, funciona normalmente.
