### ISSUE TITLE
Instalar o NVM e selecionar a versão 14.7.0 do NodeJS

### ISSUE THREAD

**Issue by gabidepizol** [GuenkaTreinamentos/treinamentos#2]
### Para windows

1. entrar no link: https://github.com/coreybutler/nvm-windows/releases
2. em assets, fazer o download nvm-setup.zip
3. descompactar o .zip e executar o aplicativo
4. siga o passo a passo da instalação
5. depois de instalado, abra o prompt de comando
5. digite os seguintes comandos:
nvm
nvm list (para listar todas as versões de node que você tem instalado na sua máquina)
nvm install 14.7.0
nvm use 14.7.0

6. para confirmar que está usando a versão do node 14.7.0 digite o comando:
node -v

### Para linux
1. abrir o shell e digitar os comandos:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm
nvm install 14.7.0

no ubuntu, automaticamente irá mudar para a versão que foi baixada.

para mais comandos, é só ir no link do nvm para linux e mac: https://github.com/nvm-sh/nvm

**Comment by devvaneio** [comment]
@gabidepizol, se tiver tudo certo, pode fechar a issue e mover o card no trello.
