### ISSUE TITLE
Módule schedule

### ISSUE THREAD

**Issue by renandmc** [GuenkaTreinamentos/treinamentos#21]
No momento estou estudando Koa e hapi para ter uma ideia do funcionamento deles, não tive experiencia com nenhum deles antes...

Pesquisando sobre ordenação e embaralhamento, achei esse pacote que pode ser útil
[node-shuffle](https://github.com/troygoode/node-shuffle)

**Comment by tashima42** [comment]
Esse vídeo aqui me ajudou bastante a pegar o básico do Koa: https://youtu.be/z84uTk5zmak
