### ISSUE TITLE
(Windows) Instalação do Docker em sua máquina, rode um container do MongoDB. 

### ISSUE THREAD

**Issue by gabibobra** [GuenkaTreinamentos/treinamentos#3]
- Para a instalação do Docker no Windows (x64 no meu caso) entrar no [site do Docker](https://www.docker.com/get-started) e na opção Docker Desktop, clickar em Download for Windows.

- Depois que o download for concluído, achar o arquivo executável Docker Desktop Installer em sua respectiva pasta usada para downloads (ou na pasta que voce escolheu baixar o instalador) e executa-lo.
> Caso apareça a tela de permissão de aplicativos do windows, selecionar SIM.
> Caso não queira um icone no seu desktop desmarque a opção referente e confirme a instalação clickando em OK.

- A instalação prosseguirá e apos o término uma tela mostrando a versão do docker instalada (2.3.0.4 caso instalada diretamente pelo site), com a frase Installation Succeeded e um botão Close, clicke nesse botão e o Docker já esta instalado.

- Para criar o container de MongoDb acessei o https://hub.docker.com/ e procurei a imagem do MongoDb, fiz a instalação da imagem disponivel em https://hub.docker.com/_/mongo sem utilizar uma versão especifica (instala a ultima versão disponivel) - para tal instalação abra o Prompt de Comando e digite: **docker pull mongo**
> Caso queira uma versão especifica olhar em https://hub.docker.com/_/mongo e rodar o comando docker pull mongo:versão_desejada.

- Depois disso ainda no prompt de comando rode a linha:  **docker run -d -p 27017:27017 --name treinamento_docker_mongodb mongo**

> A porta 27017 na linha acima padrão usada pelo mongoDB - [link documentação MongoDB](https://docs.mongodb.com/manual/reference/default-mongodb-port/)
> Treinamento_docker_mongodb foi o nome que dei para o container
>  Novamente caso queira usar uma versão especifica use mongo:versão_desejada no final

**Comment by devvaneio** [comment]
@gabibobra, como funciona este trecho?
`docker run -d -p 27017-27019:27017-27019 --name treinamento_docker_mongodb mongo`

Ele está escutando conexões em um intervalo de portas? Nunca usei esta feature.
Eu geralmente rodo apenas `docker run -d -p PORT:PORT --name my-db-example mongo.` 

Se puder comentar um pouco sobre isso e também editar este trecho para apenas uma porta, vai evitar confusão.

**Comment by gabibobra** [comment]
estava usando [esse site](https://www.thepolyglotdeveloper.com/2019/01/getting-started-mongodb-docker-container-deployment/) como base, mas é isso, pelo o que entendi, as portas não precisam ser especificadas necessariamente

o comando docker run -d -p PORT:PORT --name my-db-example mongo também pode ser utilizado

**Comment by devvaneio** [comment]
@gabibobra, as portas padrão 27018 e 2709 são apenas necessárias se você estiver rodando um config server e um shard server. Quando você vai rodar apenas uma instância mongo, não há nenhuma necessidade disso. Mas acho interessante a gente criar uma issue para você trazer mais informações sobre config server e shard server, o que acha? Também sugiro novamente que edit este trecho e deixe apenas `27017:27017` e nesta outra issue você traga este tópico para discussão.

**Comment by devvaneio** [comment]
Sobre esta outra issue, eu irei criar uma tarefa e ela irá para o backlog. Mas antes de iniciá-la, vamos encerrar o ciclo destas tarefas iniciais. Isso não impede você de pesquisar a respeito, se quiser.

**Comment by gabibobra** [comment]
entendi agora a questão, posso pesquisar sobre sim. Quando estiver completamente entendida eu upo a issue para todo mundo poder entender também. Já editei a linha referida
