### ISSUE TITLE
Instalação Yarn 1.22.4

### ISSUE THREAD

**Issue by renandmc** [GuenkaTreinamentos/treinamentos#4]
_OBS: Necessário ter previamente instalado **node** e **npm**_

**Windows**
Abrir o Windows PowerShell como Administrador (atalho `win+x`).
Digitar `npm install -g yarn`.
Aguardar a instalação.
Fechar PowerShell e abrir novamente.

**Linux (Ubuntu e derivados)**
Abrir o Terminal (atalho `ctrl+alt+t`).
Digitar `sudo npm install -g yarn`.
Digitar a senha.
Aguardar a instalação.
Fechar Terminal e abrir novamente.

**Verificar instalação e versão do Yarn**
Abrir o PowerShell ou Terminal e digitar `yarn --version`.

**Comment by arrudaluiz** [comment]
Pelo Linux, foi necessário instalar a [versão clássica](https://classic.yarnpkg.com/en/docs/install#debian-stable) do Yarn direto no sistema, pois essa instalação do [Yarn 2 através do NPM](https://yarnpkg.com/getting-started/install#global-install) não tem privilégios para instalar o Vue, forçando a usar o próprio NPM.

**Comment by arrudaluiz** [comment]
Pelo Linux, foi necessário instalar a [versão clássica](https://classic.yarnpkg.com/en/docs/install#debian-stable) do Yarn direto no sistema, pois essa instalação do [Yarn 2 através do NPM](https://yarnpkg.com/getting-started/install#global-install) não tem privilégios para instalar o Vue, forçando a usar o próprio NPM.

**Comment by renandmc** [comment]
Não entendi, essa instalação é a do Yarn 1, o Yarn 2, como diz no [site](https://yarnpkg.com/getting-started/install) é instalado como dependência em cada projeto.
Testei aqui no wsl do ubuntu no windows e esse comando rodou normal.
