### ISSUE TITLE
Criando um projeto Vue com a CLI

### ISSUE THREAD

**Issue by tashima42** [GuenkaTreinamentos/treinamentos#5]
Todo o processo descrito a seguir é feito utilizando uma CLI, o que pode variar de acordo com seu OS, porém todos os comandos devem ser os mesmos.

___

## Instalando a CLI
Antes de instalar a Vue CLI, é necessário ter o [node](https://github.com/GuenkaTreinamentos/treinamentos/issues/2) e o [Yarn](https://github.com/GuenkaTreinamentos/treinamentos/issues/4) atualizados.

Se você não possui a Vue CLI instalada em seu computador, instale o Vue com `yarn global add @vue/cli`
Se você já possui a Vue CLI, mas ela está desatualizada, use o comando `yarn global upgrade --latest @vue/cli`
Para testar se tudo ocorreu sem problemas, use o comando `vue --version`, a resposta deve ser parecida com `> @vue/cli 4.4.6`

## Repositório GIT
1. Clone o repositório do treinamento com `git clone "https://github.com/GuenkaTreinamentos/treinamentos.git"` 
	> Se você nunca conectou o Github ao seu computador, ele pode te pedir para fazer login
2. Navegue para a pasta do repositório `cd treinamentos`
3. Crie uma nova branch `git checkout -b seu-nome`

## Iniciando o projeto

1. Navegue até a pasta raiz do repositório
	- Para facilitar o processo, utilize o VSCode 
2. Crie uma nova pasta _clients_, onde o projeto será iniciado e navegue para ela com `mkdir clients`, `cd clients`
3. Crie um projeto Vue chamado _flashcards_
	- `vue create flashcards` 
4. Escolha as opções
	- `Manually select features` e com o <kbd>space</kbd>, selcione as opções: `Babel`, `Vuex`, `CSS Pre-processors`, `Linter / Formatter`
	- Depois, `Sass/SCSS (with dart-saas)`, `ESLint with error prevention only`, `Lint on save`, `In dedicated config files`
5. Caso você queira salvar as configurações como um _preset_, escreva <kbd>y</kbd> e dê um nome para ele, caso contrário, <kbd>n</kbd>.

## Testando  
Se tudo deu certo, seu projeto deve ter sido criado na pasta _flashcards_ 
1. Navegue até a pasta com `cd flashcards`
2. Inicie um servidor local com `yarn serve`
3. Em seu navegador, acesse o servidor no endereço [http://localhost:8080](http://localhost:8080)
4. Se tudo deu certo, os seguintes plugins devem estar listados: `babel`, `vuex`, `eslint`

## Enviando as mudanças
1. Coloque as mudanças em stage com `git add .`
2. Faça o commit delas utilizando o [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/): `git commit -m "tipo: mensagem de commit"`    
	> Escolhi o tipo `chore` para o meu commit, mas não estou completamente certo sobre isso. Se você acha que não é  a melhor opção, por favor faça um comentário explicando.
3. Envie as mudanças para o Github com `git push origin seu-nome`
4. Crie uma nova [Pull Request](https://github.com/GuenkaTreinamentos/treinamentos/compare), selecionando sua branch.
___
Para saber mais sobre outros comandos, consulte a [documentação oficial](https://cli.vuejs.org/guide/).

**Comment by devvaneio** [comment]
@Tashima42, você partiu direto para o `vue create flashcards`
Acredito que nem todo mundo tenha a CLI do vue instalada. As opções selecionadas, você pode deixar mais breve, tipo:
x, y, z, ...

Eu nunca rodo `Salve essas configurações com um preset com y`, pois nem sempre quero salvar estas configurações.

**Comment by tashima42** [comment]
@lusatiro 

> @Tashima42, você partiu direto para o `vue create flashcards`    

Adicionei uma nova seção para a instalação ou atualização da CLI.     

> Acredito que nem todo mundo tenha a CLI do vue instalada. As opções selecionadas, você pode deixar mais breve, tipo:
> x, y, z, ...

Não entendi muito bem, você pode explicar um pouco melhor?

> Eu nunca rodo `Salve essas configurações com um preset com y`, pois nem sempre quero salvar estas configurações.

Atualizei explicando as duas opções, você acha melhor deixar apenas o <kbd>n</kbd>?

**Comment by devvaneio** [comment]
@Tashima42, deixe esses passos apenas em apenas um tópico. E apenas cite a seleção necessária.

> Selecione a opção Manually select features
> Com o space, selcione as opções
> Babel
> Vuex
> CSS Pre-processors
> Linter / Formatter
> Escolha a opção Sass/SCSS (with dart-saas)
> Escolha a opção ESLint with error prevention only
> Selcione Lint on save
> Escolha a opção In dedicated config files
> Caso você queira salvar as configurações como um preset, escreva y, caso contrário, n
> Dê um nome para o preset

**Comment by tashima42** [comment]
> @Tashima42, deixe esses passos apenas em apenas um tópico. E apenas cite a seleção necessária.

Simplifiquei tudo pra diminuir o número de tópicos. Se estiver tudo certo, vou fechar o #6, atualizar com as mudanças e abrir outro PR.

**Comment by devvaneio** [comment]
Pode fechar.

**Comment by renandmc** [comment]
Acho que ficou faltando a parte da criação do pull request no repositório

**Comment by tashima42** [comment]
> Acho que ficou faltando a parte da criação do pull request no repositório

Vi que você já criou uma PR #10, mas como já tinha escrito os passos adicionais atualizei o issue mesmo assim.
