### ISSUE TITLE
shard server e config server - Conceitos

### ISSUE THREAD

**Issue by gabibobra** [GuenkaTreinamentos/treinamentos#7]
### **Shard e config servers**
Questionamentos:
Quando usar apenas uma instância e quando usar o shared server e config server?
Quais os trade-offs das duas abordagens?
### Tópico para aprendizado compartilhado
O escalonamento em banco de dados é um conceito que trata da necessidade de aumentar a capacidade de processamento e armazenamento de dados em uma aplicação, visando aumentar ou otimizar a mesma. Dito isso, podemos separar em duas abordagens de escalonamento diferentes: o vertical e o horizontal. 
A abordagem vertical consiste em aumentar a capacidade em um único servidor, seja aumentando a memória RAM, alterando a quantidades ou tipo dos discos utilizados no servidor, criando mais threads, ou seja, basicamente são ações ligadas ao hardware do servidor. Já a abordagem horizontal é o aumento da capacidade distribuindo os dados e seu processamento em diversas máquinas, acrescentando novos servidores caso necessário.
Com as duas abordagens em mente, o próprio MongoDB suporta nativamente o escalonamento horizontal através do recurso de sharding. Sharding é o particionamento, a divisão da base de dados em duas ou mais máquinas (instâncias de banco).
Agora vamos para o questionamento levantado na issue  #3. Primeiramente a minha tarefa era fazer um mini tutorial de instalação do Docker e criar um container utilizando o MongoDB, para isso me baseei [no site](https://www.thepolyglotdeveloper.com/2019/01/getting-started-mongodb-docker-container-deployment/) onde sem perceber apenas copiei a linha` docker run -d -p 27017-27019:27017-27019 --name mongodb mongo:4.0.4` que seria para o deploy da instância do mongo no container do Docker. A parte que define a porta que utilizaremos no deploy é `-p 27017-27019:27017-27019` onde o @lusatiro me atentou para o que estava acontecendo. Com esse comando usaríamos as portas 27017, 27018 e 27019, baseado nas [portas padrão do MongoDB](https://docs.mongodb.com/manual/reference/default-mongodb-port/) pode se notar que as portas são para intuitos diferentes. A porta 27017 é a porta padrão usada para instancias do mongod e mongos. A porta 27018 é a padrão usada para instancias de mongod quando usada em shard servers e a porta 27019 é a padrão quando usada em instâncias de mongod usadas em config servers. Mas qual a diferença entre essas instancias já que todas se tratam do mongod, e qual a diferença de shard e config servers.
### Mas o que são esses shard e config servers? 
Primeiramente temos que entender o que é um **sharded cluster**, que é basicamente o conjunto de nós existentes em uma instância que usa o sharding do MongoDB (particionamento). Nesse conceito de particionamento o MongoDB divide o sharded cluster em servers com funções diferentes, primeiramente as **shards**, servidores onde os dados são armazenados, cada shard contém um pedaço da base de dados particionada (escalonamento horizontal aplicado). O segundo servidor existente em um sharded cluster, o **mongos**, é um servidor que serve como um roteador de consultas, fornecendo uma interface entre a aplicação do cliente e o sharded cluster em si, ele tem a função de direcionar consultas e operações para as shards. E por último temos os **config severs**, que como o nome já sugere, se trata do servidor de configuração onde são armazenados metadados que são necessários para gerenciar a distribuição de dados entre as shardsl, ou seja gerencia o estado e a organização dos dados e componentes no sharded cluster.
[Imagem para melhor entendimento](https://docs.mongodb.com/v3.0/_images/sharded-cluster.png)
### Vantagens de usar do sharding

- Melhor desempenho na leitura e escrita – Com as manipulações de leitura e escrita distribuídas nas shards, cada shard utiliza menos recursos do servidor para tais manipulações já que a quantidade de dados tratados em cada uma é menor deixando assim o processamento mais rápido.
- Capacidade de armazenamento facilitada – a divisão dos dados nas shards permite que cada uma contenha um subconjunto do conjunto total de dados e quando esse total cresce shards podem ser adicionadas para aumentar a capacidade da aplicação.
- Alta disponibilidade – como os dados estão particionados mesmo que um servidor esteja inacessível, os outros podem continuar funcionando parcialmente. Possibilidade de replica das shards aumenta mais ainda a disponibilidade.
### Considerações antes de usar o sharding
- A estrutura para compor uma infraestrutura de sharded cluster tem complexidade e requisitos que necessitam de planejamento, execução e manutenção cuidadosa.
- Quando um projeto é particionado com o sharding, o MongoDB não fornece ferramenta para “desparticionar” esse projeto.
### Conclusão
Como o caso que estamos tratando seria uma aplicação simples não vejo a necessidade de usar o sharding visando o escalonamento horizontal. Com isso, já que não faremos uso de shard e config servers, a linha de comando que mais se adequa ao nosso uso seria `docker run -d -p 27017:27017 –name treinamento_docker_mongodb mongo` sendo que a porta a 27017 é a padrão.
[Link da documentação do MongoDB sobre sharding](https://docs.mongodb.com/manual/sharding/)

**Comment by devvaneio** [comment]
Legal, @gabibobra. Mas talvez eu tenha formulado as perguntas de forma errada. 
Vamos tentar manter breve a issues. Fale da existência das duas formas de escalonamento e coloque um link em 
cada uma delas, para caso alguém se interesse em ler mais. Os dois primeiros parágrafos irão praticamente sumir.

Foque nas particularidades do MongoDB, como em um trecho que você cita `mongod` e `mongos`, eu sei a diferença, mas acredito que nem todo mundo saiba. Uma descrição breve acompanhada de uma referência é a melhor solução para manter as coisas curtas e enxutas. 

Outra coisa, ao invés de escrever algo mais expositivo, escreva mais argumentativo, defendendo seus pontos e ideias.
