### ISSUE TITLE
(Ubuntu) Instalando o Docker e criando uma instância do MongoDB

### ISSUE THREAD

**Issue by arrudaluiz** [GuenkaTreinamentos/treinamentos#8]
# Instalando o Docker e criando uma instância do MongoDB no Ubuntu

### Pré-requisitos

Para instalar o Docker, é necessária a versão 64-bit de uma dessas versões do Ubuntu:

- Ubuntu Focal 20.04 (LTS)
- Ubuntu Eoan 19.10
- Ubuntu Bionic 18.04 (LTS)
- Ubuntu Xenial 16.04 (LTS)

### Instalando através do repositório oficial

Para facilitar as tarefas de instalação e atualização, é recomendado adicionar o repositório do Docker e instalá-lo a partir dele.

#### Configurar o repositório

1. Atualize a lista de pacotes do sistema:

```bash
sudo apt-get update
```

2. Instale os seguintes pacotes para permitir que o gerenciador utilize um repositório através de HTTPS:

```bash
sudo apt-get install \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common
```

3. Adicione a *GPG key* oficial do Docker:

```bash
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
```

4. Adicione o repositório da versão amd64 *stable*:

```bash
sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"
```

#### Instalar o Docker

1. Atualize a lista de pacotes do sistema:

```bash
sudo apt-get update
```

2. Instale a versão mais recente do Docker:

```bash
sudo apt-get install docker-ce docker-ce-cli containerd.io
```

3. Verifique a instalação do Docker:

```bash
sudo docker run hello-world
```

> Este comando baixa uma imagem de teste e a executa em um container. Uma mensagem será impressa se o container for executado corretamente.

## Criando um container com MongoDB

1. Baixe a imagem do *container* do MongoDB:

```bash
sudo docker pull mongo
```

O comando acima receberá a *tag* `latest`, especificando a versão mais recente da imagem. Para instalar uma versão específica, informe a *tag* da versão:

```bash
sudo docker pull mongo:TAG
```

> "TAG" é a *tag* que especifica a versão desejada da imagem do container. [Tags relevantes](https://hub.docker.com/_/mongo).

2. Inicie uma instância do servidor mongo:

```bash
sudo docker run --publish PORT:PORT --name SOME-MONGO --detach mongo:TAG
```

> "PORT" é a porta utilizada pelo Docker para acesso ao *container* no *host* especificada pelo parâmetro `--publish`.
> "SOME-MONGO" é o nome atribuído ao *container* através do parâmetro `--name`.
> O parâmetro `--detach` indica ao Docker para imprimir o *ID* do *container* e manter sua instância executando em segundo plano.
> A declaração dos parâmetros `--detach` e `--publish` pode ser abreviada para `-d` e `-p` respectivamente.

Por padrão, segundo a [documentação oficial](https://docs.mongodb.com/manual/reference/default-mongodb-port), 27017 é a porta utilizada em instâncias do MongoDB.

**Comment by devvaneio** [comment]
@arrudaluiz, no passo 3 você usou o comando `sudo` na frente do comando `docker`. Algumas configurações
são necessárias para que o Docker execute sem a permissão do super usuário. Na parte de criação do container você já não usa, isso iria apresentar um erro. Inclua esta parte na sua descrição. Ao invés de `--publish,` você poderia usar `-p` também.

Outra coisa, se você não usa a flag `-d`, o mongo vai rodar o processo em _foreground_, o que não é a intenção.
Inclua esta flag para que o processo rode em _background_. E também adicione um comando para
visualizar se o container está executando normalmente.

**Comment by arrudaluiz** [comment]
> @arrudaluiz, no passo 3 você usou o comando `sudo` na frente do comando `docker`. Algumas configurações
> são necessárias para que o Docker execute sem a permissão do super usuário. Na parte de criação do container você já não usa, isso iria apresentar um erro. Inclua esta parte na sua descrição.

Corrigido.

> Ao invés de `--publish,` você poderia usar `-p` também.
> 
> Outra coisa, se você não usa a flag `-d`, o mongo vai rodar o processo em _foreground_, o que não é a intenção.
> Inclua esta flag para que o processo rode em _background_. E também adicione um comando para
> visualizar se o container está executando normalmente.

No caso, a *flag* `-d` é a *shorthand* de `--detach`. Optei por utilizar os nomes das *flags* ao invés de suas *shorthands* por ser um padrão utilizado na criação de *shell scripts*, mas adicionei esse detalhe à descrição.

**Comment by devvaneio** [comment]
>  por ser um padrão utilizado na criação de shell scripts

Interessante isso, se tiver uma referência para eu saber mais, deixe aqui.

Pode fechar a issue caso esteja completa.
